Problem: stakepool.nix: Cannot import without configuring
If you add stakepool.nix to imports, you need to define
services.tezos.nodes, or you'll get:

    error: The option 'services.tezos.nodes' is used but not defined.

Solution: Provide a default.